apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ai-product-insights
type: Opaque
stringData:
  POSTGRES_USER: app_user
  POSTGRES_PASSWORD: app_password
  POSTGRES_DB: product_insights
